[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "!has('nvim')"
on_i = 1
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.config/nvim/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = ['toml']

# nvim-r plugins
[[plugins]]
repo= 'jalvesaq/Nvim-R'
on_ft = ['rmd','r']
hook_source = '''
  source ~/.config/nvim/plugins/Nvim-R.rc.vim
'''

[[plugins]]
repo= 'roxma/nvim-completion-manager'
on_ft = ['rmd','r']

[[plugins]]
repo= 'gaalcaras/ncm-R'
on_ft = ['rmd','r']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
  source ~/.config/nvim/plugins/deoplete.rc.vim
'''

# pythonの補完機能
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'
