[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "!has('nvim')"
on_i = 1
hook_source = '''
    let g:neocomplete#enable_at_startup = 1
    source ~/.config/nvim/plugins/neocomplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo= 'jalvesaq/Nvim-R'
on_ft = ['rmd','r']
hook_source = '''
source ~/.config/nvim/plugins/Nvim-R.rc.vim
'''
